/*==============================================================
  
  Phase        : 2.3 Customer Analysis
  Analysis     : 2.3.1 Customer KPIs
  Description  : Calculate customer-related KPIs including
                 unique customers and average orders per
                 customer.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Customer KPI Calculation
--------------------------------------------------------------*/
WITH customer_kpis AS (

    SELECT

        COUNT(DISTINCT o.order_id) AS total_orders,

        COUNT(DISTINCT c.customer_id) AS customer_records,

        COUNT(DISTINCT c.customer_unique_id) AS unique_customers

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    WHERE o.order_status = 'delivered'
)


/*--------------------------------------------------------------
 Step 2: Generate KPI Report
--------------------------------------------------------------*/
SELECT

    total_orders,

    customer_records,

    unique_customers,

    ROUND(
        total_orders::NUMERIC
        /
        NULLIF(unique_customers,0),
        2
    ) AS avg_orders_per_customer

FROM customer_kpis;

/*==============================================================
 
  Analysis     : 2.3.2 New vs Repeat Customers
  Description  : Identify one-time and repeat customers based
                 on delivered orders.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Calculate Orders per Customer
--------------------------------------------------------------*/
WITH customer_orders AS (

    SELECT

        c.customer_unique_id,

        COUNT(DISTINCT o.order_id) AS total_orders

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        c.customer_unique_id
)


/*--------------------------------------------------------------
 Step 2: Customer Classification Summary
--------------------------------------------------------------*/
SELECT

    COUNT(*) AS total_unique_customers,

    COUNT(
        CASE
            WHEN total_orders = 1 THEN 1
        END
    ) AS one_time_customers,

    COUNT(
        CASE
            WHEN total_orders > 1 THEN 1
        END
    ) AS repeat_customers,

    ROUND(
        COUNT(
            CASE
                WHEN total_orders > 1 THEN 1
            END
        )::NUMERIC
        /
        COUNT(*) * 100,
        2
    ) AS repeat_customer_pct

FROM customer_orders;

/*==============================================================
  Project      : Olist E-Commerce Analysis
  Phase        : 2.3 Customer Analysis
  Analysis     : 2.3.3 Observed Customer Lifetime Value
  Description  : Calculate the total revenue generated by each
                 unique customer during the available dataset
                 period and rank customers by customer value.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Calculate Revenue at the Order Level
--------------------------------------------------------------*/
WITH order_revenue AS (

    SELECT
        o.order_id,
        c.customer_unique_id,
        SUM(oi.price) AS order_revenue,
        COUNT(oi.order_item_id) AS total_items

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        o.order_id,
        c.customer_unique_id
),


/*--------------------------------------------------------------
 Step 2: Aggregate Metrics at the Customer Level
--------------------------------------------------------------*/
customer_value AS (

    SELECT
        customer_unique_id,

        COUNT(DISTINCT order_id) AS total_orders,

        SUM(total_items) AS total_items_purchased,

        SUM(order_revenue) AS customer_lifetime_value,

        AVG(order_revenue) AS average_order_value

    FROM order_revenue

    GROUP BY
        customer_unique_id
)


/*--------------------------------------------------------------
 Step 3: Rank Customers by Lifetime Value
--------------------------------------------------------------*/
SELECT

    DENSE_RANK() OVER (
        ORDER BY customer_lifetime_value DESC
    ) AS customer_value_rank,

    customer_unique_id,

    total_orders,

    total_items_purchased,

    ROUND(
        customer_lifetime_value::NUMERIC,
        2
    ) AS customer_lifetime_value,

    ROUND(
        average_order_value::NUMERIC,
        2
    ) AS average_order_value

FROM customer_value

ORDER BY
    customer_value_rank,
    customer_unique_id;
	
/*==============================================================
 
  Analysis     : 2.3.4 Customer Value Segmentation
  Description  : Segment customers based on observed lifetime
                 value and summarize each customer segment.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Calculate Customer Lifetime Value
--------------------------------------------------------------*/
WITH order_revenue AS (

    SELECT
        o.order_id,
        c.customer_unique_id,
        SUM(oi.price) AS order_revenue

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        o.order_id,
        c.customer_unique_id
),


customer_clv AS (

    SELECT

        customer_unique_id,

        COUNT(DISTINCT order_id) AS total_orders,

        SUM(order_revenue) AS customer_lifetime_value

    FROM order_revenue

    GROUP BY customer_unique_id
),


/*--------------------------------------------------------------
 Step 2: Assign Customer Segment
--------------------------------------------------------------*/
customer_segments AS (

    SELECT

        customer_unique_id,

        total_orders,

        customer_lifetime_value,

        CASE

            WHEN customer_lifetime_value >= 3000
                THEN 'VIP'

            WHEN customer_lifetime_value >= 1000
                THEN 'High Value'

            WHEN customer_lifetime_value >= 500
                THEN 'Medium Value'

            ELSE 'Low Value'

        END AS customer_segment

    FROM customer_clv
)


/*--------------------------------------------------------------
 Step 3: Segment Summary
--------------------------------------------------------------*/
SELECT

    customer_segment,

    COUNT(*) AS total_customers,

    ROUND(
        COUNT(*)::NUMERIC
        /
        SUM(COUNT(*)) OVER() * 100,
        2
    ) AS customer_percentage,

    ROUND(
        SUM(customer_lifetime_value)::NUMERIC,
        2
    ) AS total_segment_revenue,

    ROUND(
        AVG(customer_lifetime_value)::NUMERIC,
        2
    ) AS average_customer_value,

    ROUND(
        SUM(customer_lifetime_value)
        /
        SUM(SUM(customer_lifetime_value)) OVER() * 100,
        2
    ) AS revenue_share_pct

FROM customer_segments

GROUP BY customer_segment

ORDER BY

    CASE customer_segment

        WHEN 'VIP' THEN 1
        WHEN 'High Value' THEN 2
        WHEN 'Medium Value' THEN 3
        ELSE 4

    END;

/*==============================================================
 
  Analysis     : 2.3.5 Customer Revenue Concentration Summary
  Description  : Identify how many customers contribute
                 50%, 80%, and 90% of total revenue.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Calculate Customer Lifetime Value
--------------------------------------------------------------*/
WITH order_revenue AS (

    SELECT
        o.order_id,
        c.customer_unique_id,
        SUM(oi.price) AS order_revenue

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        o.order_id,
        c.customer_unique_id
),

customer_clv AS (

    SELECT

        customer_unique_id,

        SUM(order_revenue) AS customer_lifetime_value

    FROM order_revenue

    GROUP BY customer_unique_id
),

pareto AS (

    SELECT

        customer_unique_id,

        customer_lifetime_value,

        ROW_NUMBER() OVER (
            ORDER BY customer_lifetime_value DESC
        ) AS customer_rank,

        COUNT(*) OVER () AS total_customers,

        SUM(customer_lifetime_value) OVER (
            ORDER BY customer_lifetime_value DESC
        ) AS cumulative_revenue,

        SUM(customer_lifetime_value) OVER () AS total_revenue

    FROM customer_clv
)


/*--------------------------------------------------------------
 Step 2: Pareto Summary
--------------------------------------------------------------*/
SELECT

    MIN(
        CASE
            WHEN cumulative_revenue >= total_revenue * 0.50
            THEN customer_rank
        END
    ) AS customers_for_50_percent_revenue,

    MIN(
        CASE
            WHEN cumulative_revenue >= total_revenue * 0.80
            THEN customer_rank
        END
    ) AS customers_for_80_percent_revenue,

    MIN(
        CASE
            WHEN cumulative_revenue >= total_revenue * 0.90
            THEN customer_rank
        END
    ) AS customers_for_90_percent_revenue,

    MAX(total_customers) AS total_customers

FROM pareto;

/*==============================================================
 
  Analysis     : 2.3.6 Average Customer Spend
  Description  : Calculate average customer spending behavior
                 across all delivered orders.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Customer-Level Metrics
--------------------------------------------------------------*/
WITH customer_summary AS (

    SELECT

        c.customer_unique_id,

        COUNT(DISTINCT o.order_id) AS total_orders,

        COUNT(oi.order_item_id) AS total_items,

        SUM(oi.price) AS total_spend

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        c.customer_unique_id
)


/*--------------------------------------------------------------
 Step 2: Overall Customer Spending Metrics
--------------------------------------------------------------*/
SELECT

    COUNT(*) AS total_customers,

    ROUND(AVG(total_spend)::NUMERIC,2) AS average_customer_spend,

    ROUND(AVG(total_orders)::NUMERIC,2) AS average_orders_per_customer,

    ROUND(AVG(total_items)::NUMERIC,2) AS average_items_per_customer

FROM customer_summary;

/*==============================================================
 
  Analysis     : 2.3.7 RFM Customer Segmentation
  Description  : Calculate Recency, Frequency and Monetary
                 metrics and assign tie-safe RFM scores.
==============================================================*/


/*--------------------------------------------------------------
 Step 1: Calculate Customer-Level RFM Metrics
--------------------------------------------------------------*/

WITH customer_rfm AS (

    SELECT
        c.customer_unique_id,

        MAX(o.order_purchase_timestamp)::DATE
            AS last_purchase_date,

        COUNT(DISTINCT o.order_id)
            AS frequency,

        SUM(oi.price)
            AS monetary

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        c.customer_unique_id
),


/*--------------------------------------------------------------
 Step 2: Identify the Analysis Date

 The latest delivered-order purchase date is used as the
 reference date for calculating customer recency.
--------------------------------------------------------------*/

analysis_date AS (

    SELECT
        MAX(order_purchase_timestamp)::DATE
            AS max_purchase_date

    FROM orders

    WHERE order_status = 'delivered'
),


/*--------------------------------------------------------------
 Step 3: Calculate Base RFM Values
--------------------------------------------------------------*/

rfm_base AS (

    SELECT
        cr.customer_unique_id,

        ad.max_purchase_date
            - cr.last_purchase_date
            AS recency_days,

        cr.frequency,

        ROUND(
            cr.monetary::NUMERIC,
            2
        ) AS monetary

    FROM customer_rfm cr

    CROSS JOIN analysis_date ad
),


/*--------------------------------------------------------------
 Step 4: Calculate Percentile Position for Distinct Recency Values

 Lower recency is better.

 Distinct values are used so customers with identical recency
 receive the same score.
--------------------------------------------------------------*/

recency_percentiles AS (

    SELECT
        recency_days,

        PERCENT_RANK() OVER (
            ORDER BY recency_days ASC
        ) AS recency_percentile

    FROM (

        SELECT DISTINCT
            recency_days

        FROM rfm_base

    ) distinct_recency
),


/*--------------------------------------------------------------
 Step 5: Calculate Percentile Position for Distinct Frequencies

 Higher frequency is better.

 Distinct values prevent customers with the same order count
 from receiving different scores.
--------------------------------------------------------------*/

frequency_percentiles AS (

    SELECT
        frequency,

        PERCENT_RANK() OVER (
            ORDER BY frequency ASC
        ) AS frequency_percentile

    FROM (

        SELECT DISTINCT
            frequency

        FROM rfm_base

    ) distinct_frequency
),


/*--------------------------------------------------------------
 Step 6: Calculate Percentile Position for Distinct Monetary Values

 Higher monetary value is better.

 Distinct values ensure identical spending values receive
 identical scores.
--------------------------------------------------------------*/

monetary_percentiles AS (

    SELECT
        monetary,

        PERCENT_RANK() OVER (
            ORDER BY monetary ASC
        ) AS monetary_percentile

    FROM (

        SELECT DISTINCT
            monetary

        FROM rfm_base

    ) distinct_monetary
),


/*--------------------------------------------------------------
 Step 7: Join Percentile Values Back to Each Customer
--------------------------------------------------------------*/

rfm_percentiles AS (

    SELECT
        rb.customer_unique_id,

        rb.recency_days,

        rb.frequency,

        rb.monetary,

        rp.recency_percentile,

        fp.frequency_percentile,

        mp.monetary_percentile

    FROM rfm_base rb

    INNER JOIN recency_percentiles rp
        ON rb.recency_days = rp.recency_days

    INNER JOIN frequency_percentiles fp
        ON rb.frequency = fp.frequency

    INNER JOIN monetary_percentiles mp
        ON rb.monetary = mp.monetary
),


/*--------------------------------------------------------------
 Step 8: Convert Percentiles into RFM Scores from 1 to 5
--------------------------------------------------------------*/

rfm_scores AS (

    SELECT
        customer_unique_id,

        recency_days,

        frequency,

        monetary,

        CASE
            WHEN recency_percentile <= 0.20 THEN 5
            WHEN recency_percentile <= 0.40 THEN 4
            WHEN recency_percentile <= 0.60 THEN 3
            WHEN recency_percentile <= 0.80 THEN 2
            ELSE 1
        END AS recency_score,

        CASE
            WHEN frequency_percentile >= 0.80 THEN 5
            WHEN frequency_percentile >= 0.60 THEN 4
            WHEN frequency_percentile >= 0.40 THEN 3
            WHEN frequency_percentile >= 0.20 THEN 2
            ELSE 1
        END AS frequency_score,

        CASE
            WHEN monetary_percentile >= 0.80 THEN 5
            WHEN monetary_percentile >= 0.60 THEN 4
            WHEN monetary_percentile >= 0.40 THEN 3
            WHEN monetary_percentile >= 0.20 THEN 2
            ELSE 1
        END AS monetary_score

    FROM rfm_percentiles
),


/*--------------------------------------------------------------
 Step 9: Generate Combined RFM Score
--------------------------------------------------------------*/

rfm_combined AS (

    SELECT
        customer_unique_id,

        recency_days,

        frequency,

        monetary,

        recency_score,

        frequency_score,

        monetary_score,

        CONCAT(
            recency_score,
            frequency_score,
            monetary_score
        ) AS rfm_score

    FROM rfm_scores
),


/*--------------------------------------------------------------
 Step 10: Assign Customer Segments
--------------------------------------------------------------*/

customer_segments AS (

    SELECT
        customer_unique_id,

        recency_days,

        frequency,

        monetary,

        recency_score,

        frequency_score,

        monetary_score,

        rfm_score,

        CASE

            /* Recent, frequent and high-spending customers */
            WHEN recency_score >= 4
             AND frequency_score >= 4
             AND monetary_score >= 4
                THEN 'Champions'

            /* Customers with consistently strong RFM behaviour */
            WHEN recency_score >= 3
             AND frequency_score >= 3
             AND monetary_score >= 3
                THEN 'Loyal Customers'

            /* Most recent customers who have purchased once */
            WHEN recency_score = 5
             AND frequency_score = 1
                THEN 'New Customers'

            /* High-spending customers with limited frequency */
            WHEN monetary_score = 5
             AND frequency_score <= 2
             AND recency_score >= 3
                THEN 'Big Spenders'

            /* Recent customers with potential to purchase again */
            WHEN recency_score >= 4
             AND frequency_score <= 2
                THEN 'Potential Loyalists'

            /* Fairly recent one-time customers */
            WHEN recency_score = 4
             AND frequency_score = 1
                THEN 'Promising'

            /* Customers showing moderate inactivity */
            WHEN recency_score = 3
             AND frequency_score <= 2
                THEN 'Need Attention'

            /* Previously valuable customers who are becoming inactive */
            WHEN recency_score <= 2
             AND (
                    frequency_score >= 3
                    OR monetary_score >= 4
                 )
                THEN 'At Risk'

            /* Inactive one-time, low-to-medium-value customers */
            WHEN recency_score = 1
             AND frequency_score = 1
                THEN 'Lost Customers'

            ELSE 'Regular Customers'

        END AS customer_segment

    FROM rfm_combined
)


/*--------------------------------------------------------------
 Step 11: Display Final Customer-Level RFM Segmentation
--------------------------------------------------------------*/

SELECT
    customer_unique_id,

    recency_days,

    frequency,

    monetary,

    recency_score,

    frequency_score,

    monetary_score,

    rfm_score,

    customer_segment

FROM customer_segments

ORDER BY
    recency_score DESC,
    frequency_score DESC,
    monetary_score DESC,
    monetary DESC;

